<a href="https://colab.research.google.com/github/wasgingschief/wasgingschief-Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [4]:
x = np.array([1, 3])
print(x)

[1 3]


In [5]:
x.ndim

1

In [6]:
x.shape

(2,)

In [7]:
x.size

2

In [8]:
x.dtype

dtype('int64')

In [9]:
x = np.array([1.3, 2.3, 1.3])
print(x)

[1.3 2.3 1.3]


In [10]:
x.dtype

dtype('float64')

Dwuwymiarowa tablica - macierz

In [11]:
x = np.array([[1, 2], [-3, 1]])
print(x)


[[ 1  2]
 [-3  1]]


In [12]:
x.ndim

2

In [13]:
x.shape

(2, 2)

In [14]:
x.dtype

dtype('int64')

In [15]:
x = np.array(([[1, 2, 3], [4, 2, 1]]))
print(x)

[[1 2 3]
 [4 2 1]]


Trójwymiarowa

In [16]:

x = np.array([
    [
        [[4, 3, 1],
         [3, 1, 2]],

        [[4, 1, 3],
         [4, 2, 1]]
    ]
])

x

array([[[[4, 3, 1],
         [3, 1, 2]],

        [[4, 1, 3],
         [4, 2, 1]]]])

In [17]:
x.ndim

4

In [18]:
A = np.array([1.0, 2.3, 1], dtype = 'float')
A.dtype

dtype('float64')

In [19]:
A

array([1. , 2.3, 1. ])

In [ ]:
A = np.array([1.0, 2.3, 1], dtype = 'int')
A.dtype

dtype('int64')

In [20]:
A

array([1. , 2.3, 1. ])

In [21]:
a = np. array([True, False])
a.dtype

dtype('bool')

In [22]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [28]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [29]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [30]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a = np.array ([3, 1, 4, 2])
b = np.array([3, -1, 3, 2])
print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  2]


In [33]:
a + b

array([6, 0, 7, 4])

In [34]:
np.subtract(a, b)

array([0, 2, 1, 0])

In [35]:
np.add(a, b)

array([6, 0, 7, 4])

In [36]:
x = np.array([[1, 3],[-2, 0]])
y = np.array([[6, 0], [-1, 2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [37]:
np.dot(x, y)

array([[  3,   6],
       [-12,   0]])

In [38]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [39]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [40]:
x @ y

array([[  3,   6],
       [-12,   0]])

In [42]:
np.random.seed(0)

In [43]:
np.random.randn()

1.764052345967664

In [44]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [47]:
np.random.randn(10, 4)

array([[ 1.22244507,  0.20827498,  0.97663904,  0.3563664 ],
       [ 0.70657317,  0.01050002,  1.78587049,  0.12691209],
       [ 0.40198936,  1.8831507 , -1.34775906, -1.270485  ],
       [ 0.96939671, -1.17312341,  1.94362119, -0.41361898],
       [-0.74745481,  1.92294203,  1.48051479,  1.86755896],
       [ 0.90604466, -0.86122569,  1.91006495, -0.26800337],
       [ 0.8024564 ,  0.94725197, -0.15501009,  0.61407937],
       [ 0.92220667,  0.37642553, -1.09940079,  0.29823817],
       [ 1.3263859 , -0.69456786, -0.14963454, -0.43515355],
       [ 1.84926373,  0.67229476,  0.40746184, -0.76991607]])

In [48]:
np.random.rand()

0.5210366062041293

In [49]:
np.random.rand(10)

array([0.05433799, 0.19999652, 0.01852179, 0.7936977 , 0.22392469,
       0.34535168, 0.92808129, 0.7044144 , 0.03183893, 0.16469416])

In [50]:
np.random.rand(10, 2)

array([[0.6214784 , 0.57722859],
       [0.23789282, 0.934214  ],
       [0.61396596, 0.5356328 ],
       [0.58990998, 0.73012203],
       [0.311945  , 0.39822106],
       [0.20984375, 0.18619301],
       [0.94437239, 0.7395508 ],
       [0.49045881, 0.22741463],
       [0.25435648, 0.05802916],
       [0.43441663, 0.31179588]])

In [51]:
np.random.randint(10)

2

In [52]:
np.random.randint(low=10, high=101)

53

In [53]:
np.random.randint(low=10, high=101, size=10)

array([93, 59, 51, 56, 31, 83, 99, 83, 38, 91])

In [54]:
np.random.choice(['python', 'java', 'sql'])

np.str_('java')

In [55]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.random.shuffle(data)
data

array([1, 3, 8, 5, 4, 2, 9, 7, 6, 0])

In [57]:
data

array([1, 3, 8, 5, 4, 2, 9, 7, 6, 0])

Podstawowe funkcje


In [58]:
np.exp(1)

np.float64(2.718281828459045)

In [59]:
np.exp(2)

np.float64(7.38905609893065)

In [60]:
np.sqrt(9)

np.float64(3.0)

In [62]:
np.all([2, 3, 0])

np.False_

In [63]:
np.all([2, 3, 1])

np.True_

In [64]:
np.any([2, 3, 0])

np.True_

In [65]:
np.any([0, 0, 0])

np.False_

In [67]:
bool(1)

True

In [70]:
A = np.random.rand(5)
A

array([0.45612977, 0.48340862, 0.78873943, 0.22944183, 0.8802976 ])

In [71]:
np.argmax(A) #indeks największa wartość

np.int64(4)

In [72]:
A[np.argmax(A)] #największa wartość

np.float64(0.8802976031150046)

In [73]:
np.argmin(A) # indeks najmniejsza wartość

np.int64(3)

In [74]:
np.argsort(A) #sortuje

array([3, 0, 1, 2, 4])

In [75]:
np.max(A) #największa wartość

np.float64(0.8802976031150046)

In [76]:
np.min(A) #najmnijesza wartość

np.float64(0.22944183447104538)

In [77]:
np.mean(A) #średnia

np.float64(0.5676034507679402)

In [78]:
np.median(A) #mediana

np.float64(0.48340861659875267)

In [79]:
np.std(A) #odchylenie standardowe

np.float64(0.23687430548686852)

INDESKOWANIE I WYCINANIE

In [81]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
A[2]

np.int64(2)

In [83]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [84]:
A[:2]

array([0, 1])

In [85]:
A[[0, 2]]

array([0, 2])

In [86]:
A[-1]

np.int64(19)

In [87]:
A[10:15]

array([10, 11, 12, 13, 14])

In [91]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
A[0]

array([0, 1, 2, 3, 4])

In [93]:
A[1] #zwraca wiersz

array([5, 6, 7, 8, 9])

In [94]:
A[:, 0] #zwraca kolumnę

array([ 0,  5, 10, 15])

In [95]:
A[:, -1]

array([ 4,  9, 14, 19])

In [96]:
A[1,1] #wycinanie pojedynczego elementu

np.int64(6)

In [97]:
A[1, 3]

np.int64(8)

In [99]:
A[1:3, 1:4] #wycinanie fragmentu tablicy

array([[ 6,  7,  8],
       [11, 12, 13]])

In [102]:
A[1, 2] = 14


In [103]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

ITERACJA PO TABLICACH, ZMIANA ROZMIARU ORAZ MASKI LOGICZNE

In [104]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [105]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [106]:
for row in A:
  print(row[0])

0
5
10
15


In [107]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [108]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [109]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
A.shape

(4, 5)

In [111]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [112]:
A.ravel() #wypłaszcza dane - postac jednowymiarowa

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [113]:
A.T #transponowanie

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [120]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [121]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [122]:
A < 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [123]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [124]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [125]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])