<a href="https://colab.research.google.com/github/wasgingschief/wasgingschief-Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
print(x)

[1 3]


In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.3])
print(x)

[1.3 2.3 1.3]


In [ ]:
x.dtype

dtype('float64')

Dwuwymiarowa tablica - macierz

In [ ]:
x = np.array([[1, 2], [-3, 1]])
print(x)


[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array(([[1, 2, 3], [4, 2, 1]]))
print(x)

[[1 2 3]
 [4 2 1]]


Trójwymiarowa

In [ ]:

x = np.array([
    [
        [[4, 3, 1],
         [3, 1, 2]],

        [[4, 1, 3],
         [4, 2, 1]]
    ]
])

x

array([[[[4, 3, 1],
         [3, 1, 2]],

        [[4, 1, 3],
         [4, 2, 1]]]])

In [ ]:
x.ndim

4

In [ ]:
A = np.array([1.0, 2.3, 1], dtype = 'float')
A.dtype

dtype('float64')

In [ ]:
A

array([1. , 2.3, 1. ])

In [ ]:
A = np.array([1.0, 2.3, 1], dtype = 'int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 1])

In [ ]:
a = np. array([True, False])
a.dtype

dtype('bool')

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a = np.array ([3, 1, 4, 2])
b = np.array([3, -1, 3, 2])
print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
a + b

array([6, 0, 7, 4])

In [ ]:
np.subtract(a, b)

array([0, 2, 1, 0])

In [ ]:
np.add(a, b)

array([6, 0, 7, 4])

In [ ]:
x = np.array([[1, 3],[-2, 0]])
y = np.array([[6, 0], [-1, 2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(x, y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
x @ y

array([[  3,   6],
       [-12,   0]])

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(low=10, high=101)

56

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([ 42,  28,  20, 100,  85,  36,  39,  90,  82,  18])

In [ ]:
np.random.choice(['python', 'java', 'sql'])

np.str_('sql')

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([7, 1, 3, 9, 2, 5, 4, 0, 8, 6])

In [ ]:
data

array([7, 1, 3, 9, 2, 5, 4, 0, 8, 6])